2020-12-18 19:54:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement """CREATE TABLE IF NOT EXISTS share_rates(""[*] +
                    ""id BIGINT AUTO_INCREMENT PRIMARY KEY,"" +
                    ""operDate datetime NOT NULL,"" +
                    ""share BIGINT NOT NULL,""+
                                                    
                            "")"",
                    ""Создана таблица "" + TABLENAME);"; SQL statement:
"CREATE TABLE IF NOT EXISTS share_rates(" +
                    "id BIGINT AUTO_INCREMENT PRIMARY KEY," +
                    "operDate datetime NOT NULL," +
                    "share BIGINT NOT NULL,"+
                    //"rate DECIMAL(1,2) NOT NULL" +
                            ")",
                    "Создана таблица " + tableName); [42000-200]
2020-12-18 19:59:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
 [90002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:231)
	at org.h2.command.CommandContainer.query(CommandContainer.java:285)
	at org.h2.command.Command.executeQuery(Command.java:195)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:85)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:34)
	at by.tc.task01.main.Main.main(Main.java:69)
2020-12-18 19:59:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
 [90002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:231)
	at org.h2.command.CommandContainer.query(CommandContainer.java:285)
	at org.h2.command.Command.executeQuery(Command.java:195)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:85)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:34)
	at by.tc.task01.main.Main.main(Main.java:69)
2020-12-18 20:00:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
 [90002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:231)
	at org.h2.command.CommandContainer.query(CommandContainer.java:285)
	at org.h2.command.Command.executeQuery(Command.java:195)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:85)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:34)
	at by.tc.task01.main.Main.main(Main.java:69)
2020-12-18 20:00:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
 [90002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:231)
	at org.h2.command.CommandContainer.query(CommandContainer.java:285)
	at org.h2.command.Command.executeQuery(Command.java:195)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:85)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:34)
	at by.tc.task01.main.Main.main(Main.java:69)
2020-12-18 20:00:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Scale($"2") must not be bigger than precision("1"); SQL statement:
CREATE TABLE IF NOT EXISTS share_rates(id BIGINT AUTO_INCREMENT PRIMARY KEY,operDate datetime NOT NULL,share BIGINT NOT NULL,rate DECIMAL(1,2) NOT NULL) [90051-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:6145)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5697)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:8442)
	at org.h2.command.Parser.parseCreateTable(Parser.java:8379)
	at org.h2.command.Parser.parseCreate(Parser.java:6276)
	at org.h2.command.Parser.parsePrepared(Parser.java:903)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:36)
	at by.tc.task01.main.Main.main(Main.java:69)
2020-12-18 20:05:53 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS SHARE_RATES(ID BIGINT AUTO_INCREMENT PRIMARY KEY,OPERDATE DATETIME NOT NULL,SHARE BIGINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS share_rates(id BIGINT AUTO_INCREMENT PRIMARY KEY,operDate datetime NOT NULL,share BIGINT NOT NULL,) [42001-200]
2020-12-18 20:05:55 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.main.Main.main(Main.java:69)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 20 more
2020-12-18 20:06:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS SHARE_RATES(ID BIGINT AUTO_INCREMENT PRIMARY KEY,OPERDATE DATETIME NOT NULL,SHARE BIGINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS share_rates(id BIGINT AUTO_INCREMENT PRIMARY KEY,operDate datetime NOT NULL,share BIGINT NOT NULL,) [42001-200]
2020-12-18 20:13:09 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,OPERDATE DATETIME NOT NULL,SHARE BIGINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,operDate datetime NOT NULL,share BIGINT NOT NULL,) [42001-200]
2020-12-18 20:15:43 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,OPERDATE DATETIME NOT NULL,SHARE BIGINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,operDate datetime NOT NULL,share BIGINT NOT NULL,) [42001-200]
2020-12-18 20:28:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:28:58 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:30:53 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.main.Main.main(Main.java:69)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 20 more
2020-12-18 20:32:14 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OVEN_TABLE" not found; SQL statement:
 ALTER TABLE oven_table ADD FOREIGN KEY (share) REFERENCES oven(id) [42102-200]
2020-12-18 20:32:57 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:35:59 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:36:37 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:38:30 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:39:37 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:40:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OVEN_TABLE" not found; SQL statement:
 ALTER TABLE oven_table ADD FOREIGN KEY (share) REFERENCES oven(id) [42102-200]
2020-12-18 20:41:38 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:46:47 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:51:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 20:58:35 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 21:22:24 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 21:23:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS OVEN_TABLE(POWERCONSUMPTION SMALLINT NOT NULL,WEIGHT REAL NOT NULL,CAPACITY REAL NOT NULL,DEPTH REAL NOT NULLHEIGHT[*] REAL NOT NULLWIDTH REAL NOT NULL)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS oven_table(PowerConsumption SMALLINT NOT NULL,Weight REAL NOT NULL,Capacity REAL NOT NULL,Depth REAL NOT NULLHeight REAL NOT NULLWidth REAL NOT NULL) [42001-200]
2020-12-18 21:43:10 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "LAPTOP" not found; SQL statement:
 ALTER TABLE oven_table ADD FOREIGN KEY (appliance) REFERENCES laptop(id) [42102-200]
2020-12-18 21:44:36 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "LAPTOP_TABLE" not found; SQL statement:
 ALTER TABLE laptop_table ADD FOREIGN KEY (appliance) REFERENCES laptop(id) [42102-200]
2020-12-18 22:01:50 jdbc[8]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "LAPTOP_TABLE" not found; SQL statement:
 ALTER TABLE laptop_table ADD FOREIGN KEY (appliance) REFERENCES laptop(id) [42102-200]
2020-12-18 22:02:08 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OVEN" not found; SQL statement:
 ALTER TABLE oven_table ADD FOREIGN KEY (appliance) REFERENCES oven(id) [42102-200]
2020-12-18 22:03:13 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "APPLIANCE" not found; SQL statement:
 ALTER TABLE oven_table ADD FOREIGN KEY (appliance) REFERENCES oven_table(id) [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:703)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:115)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:216)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at by.tc.task01.repository.BaseTable.executeSqlStatement(BaseTable.java:36)
	at by.tc.task01.repository.Oven.createForeignKeys(Oven.java:29)
	at by.tc.task01.ExchangeDB.createTablesAndForeignKeys(ExchangeDB.java:68)
	at by.tc.task01.ExchangeDB.setExchangeDB(ExchangeDB.java:86)
	at by.tc.task01.main.Main.main(Main.java:72)
2020-12-18 22:04:50 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "APPLIANCE" not found; SQL statement:
 ALTER TABLE oven_table ADD FOREIGN KEY (appliance) REFERENCES oven_table(id) [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:703)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:115)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:216)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at by.tc.task01.repository.BaseTable.executeSqlStatement(BaseTable.java:36)
	at by.tc.task01.repository.Oven.createForeignKeys(Oven.java:29)
	at by.tc.task01.ExchangeDB.createTablesAndForeignKeys(ExchangeDB.java:68)
	at by.tc.task01.ExchangeDB.setExchangeDB(ExchangeDB.java:86)
	at by.tc.task01.main.Main.main(Main.java:72)
2020-12-18 22:05:49 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
 ALTER TABLE oven_table ADD FOREIGN KEY (Depth) REFERENCES oven_table(id) [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:703)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:115)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:231)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at by.tc.task01.repository.BaseTable.executeSqlStatement(BaseTable.java:36)
	at by.tc.task01.repository.Oven.createForeignKeys(Oven.java:29)
	at by.tc.task01.ExchangeDB.createTablesAndForeignKeys(ExchangeDB.java:68)
	at by.tc.task01.ExchangeDB.setExchangeDB(ExchangeDB.java:86)
	at by.tc.task01.main.Main.main(Main.java:72)
2020-12-18 22:09:04 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
 ALTER TABLE oven_table ADD FOREIGN KEY (id) REFERENCES oven_table(id) [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:703)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:115)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:216)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at by.tc.task01.repository.BaseTable.executeSqlStatement(BaseTable.java:36)
	at by.tc.task01.repository.Oven.createForeignKeys(Oven.java:29)
	at by.tc.task01.ExchangeDB.createTablesAndForeignKeys(ExchangeDB.java:68)
	at by.tc.task01.ExchangeDB.setExchangeDB(ExchangeDB.java:86)
	at by.tc.task01.main.Main.main(Main.java:72)
2020-12-18 22:10:22 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
 ALTER TABLE oven_table ADD FOREIGN KEY (Depth) REFERENCES oven_table(id) [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:703)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:115)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:231)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at by.tc.task01.repository.BaseTable.executeSqlStatement(BaseTable.java:36)
	at by.tc.task01.repository.Oven.createForeignKeys(Oven.java:29)
	at by.tc.task01.ExchangeDB.createTablesAndForeignKeys(ExchangeDB.java:68)
	at by.tc.task01.ExchangeDB.setExchangeDB(ExchangeDB.java:86)
	at by.tc.task01.main.Main.main(Main.java:72)
2020-12-18 22:10:24 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:36)
	at by.tc.task01.main.Main.main(Main.java:69)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 20 more
2020-12-18 22:30:05 jdbc[8]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "LAPTOP_TABLE" not found; SQL statement:
 ALTER TABLE laptop_table ADD FOREIGN KEY (id) REFERENCES laptop(id) [42102-200]
2020-12-18 22:30:58 jdbc[8]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "LAPTOP_TABLE" not found; SQL statement:
 ALTER TABLE laptop_table ADD FOREIGN KEY (id) REFERENCES laptop(id) [42102-200]
2020-12-19 00:25:55 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS VACUUMCLEANER_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,FILTERTYPE NVARCHAR NOT NULL,BAGTYPE NVARCHAR NOT NULL,WANDTYPE NVARCHAR NOT NULLMOTORSPEEDREGULATION[*] SMALLINT NOT NULL,CLEANINGWIDTH SMALLINT NOT NULL,)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS vacuumCleaner_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,FilterType NVARCHAR NOT NULL,BagType NVARCHAR NOT NULL,WandType NVARCHAR NOT NULLMotorSpeedRegulation SMALLINT NOT NULL,CleaningWidth SMALLINT NOT NULL,) [42001-200]
2020-12-19 00:27:00 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS VACUUMCLEANER_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,FILTERTYPE NVARCHAR NOT NULL,BAGTYPE NVARCHAR NOT NULL,WANDTYPE NVARCHAR NOT NULLMOTORSPEEDREGULATION[*] SMALLINT NOT NULL,CLEANINGWIDTH SMALLINT NOT NULL,)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS vacuumCleaner_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,FilterType NVARCHAR NOT NULL,BagType NVARCHAR NOT NULL,WandType NVARCHAR NOT NULLMotorSpeedRegulation SMALLINT NOT NULL,CleaningWidth SMALLINT NOT NULL,) [42001-200]
2020-12-19 00:27:35 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS VACUUMCLEANER_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,FILTERTYPE NVARCHAR NOT NULL,BAGTYPE NVARCHAR NOT NULL,WANDTYPE NVARCHAR NOT NULLMOTORSPEEDREGULATION[*] SMALLINT NOT NULL,CLEANINGWIDTH SMALLINT NOT NULL,)"; expected "NULL"; SQL statement:
CREATE TABLE IF NOT EXISTS vacuumCleaner_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,FilterType NVARCHAR NOT NULL,BagType NVARCHAR NOT NULL,WandType NVARCHAR NOT NULLMotorSpeedRegulation SMALLINT NOT NULL,CleaningWidth SMALLINT NOT NULL,) [42001-200]
2020-12-19 00:28:42 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS VACUUMCLEANER_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,FILTERTYPE NVARCHAR NOT NULL,BAGTYPE NVARCHAR NOT NULL,WANDTYPE NVARCHAR NOT NULL,MOTORSPEEDREGULATION SMALLINT NOT NULL,CLEANINGWIDTH SMALLINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS vacuumCleaner_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,FilterType NVARCHAR NOT NULL,BagType NVARCHAR NOT NULL,WandType NVARCHAR NOT NULL,MotorSpeedRegulation SMALLINT NOT NULL,CleaningWidth SMALLINT NOT NULL,) [42001-200]
2020-12-19 00:32:36 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS VACUUMCLEANER_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,FILTERTYPE NVARCHAR NOT NULL,BAGTYPE NVARCHAR NOT NULL,WANDTYPE NVARCHAR NOT NULL,MOTORSPEEDREGULATION SMALLINT NOT NULL,CLEANINGWIDTH SMALLINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS vacuumCleaner_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,FilterType NVARCHAR NOT NULL,BagType NVARCHAR NOT NULL,WandType NVARCHAR NOT NULL,MotorSpeedRegulation SMALLINT NOT NULL,CleaningWidth SMALLINT NOT NULL,) [42001-200]
2020-12-19 00:34:28 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS VACUUMCLEANER_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,FILTERTYPE NVARCHAR NOT NULL,BAGTYPE NVARCHAR NOT NULL,WANDTYPE NVARCHAR NOT NULL,MOTORSPEEDREGULATION SMALLINT NOT NULL,CLEANINGWIDTH SMALLINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS vacuumCleaner_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,FilterType NVARCHAR NOT NULL,BagType NVARCHAR NOT NULL,WandType NVARCHAR NOT NULL,MotorSpeedRegulation SMALLINT NOT NULL,CleaningWidth SMALLINT NOT NULL,) [42001-200]
2020-12-19 00:35:04 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS VACUUMCLEANER_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,FILTERTYPE NVARCHAR NOT NULL,BAGTYPE NVARCHAR NOT NULL,WANDTYPE NVARCHAR NOT NULL,MOTORSPEEDREGULATION SMALLINT NOT NULL,CLEANINGWIDTH SMALLINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS vacuumCleaner_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,FilterType NVARCHAR NOT NULL,BagType NVARCHAR NOT NULL,WandType NVARCHAR NOT NULL,MotorSpeedRegulation SMALLINT NOT NULL,CleaningWidth SMALLINT NOT NULL,) [42001-200]
2020-12-19 00:36:28 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS VACUUMCLEANER_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,FILTERTYPE NVARCHAR NOT NULL,BAGTYPE NVARCHAR NOT NULL,WANDTYPE NVARCHAR NOT NULL,MOTORSPEEDREGULATION SMALLINT NOT NULL,CLEANINGWIDTH SMALLINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS vacuumCleaner_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,FilterType NVARCHAR NOT NULL,BagType NVARCHAR NOT NULL,WandType NVARCHAR NOT NULL,MotorSpeedRegulation SMALLINT NOT NULL,CleaningWidth SMALLINT NOT NULL,) [42001-200]
2020-12-19 00:38:52 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS VACUUMCLEANER_TABLE(ID BIGINT AUTO_INCREMENT PRIMARY KEY,POWERCONSUMPTION SMALLINT NOT NULL,FILTERTYPE NVARCHAR NOT NULL,BAGTYPE NVARCHAR NOT NULL,WANDTYPE NVARCHAR NOT NULL,MOTORSPEEDREGULATION SMALLINT NOT NULL,CLEANINGWIDTH SMALLINT NOT NULL,)[*]"; expected "identifier"; SQL statement:
CREATE TABLE IF NOT EXISTS vacuumCleaner_table(id BIGINT AUTO_INCREMENT PRIMARY KEY,PowerConsumption SMALLINT NOT NULL,FilterType NVARCHAR NOT NULL,BagType NVARCHAR NOT NULL,WandType NVARCHAR NOT NULL,MotorSpeedRegulation SMALLINT NOT NULL,CleaningWidth SMALLINT NOT NULL,) [42001-200]
2020-12-19 00:39:16 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:31)
	at by.tc.task01.main.Main.main(Main.java:70)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 20 more
2020-12-19 00:39:16 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:48)
	at by.tc.task01.main.Main.main(Main.java:70)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 20 more
2020-12-19 09:34:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
update oven_table set PowerConsumption='100' where id=123 [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:190)
	at org.h2.command.dml.Update.prepare(Update.java:266)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:126)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:56)
	at by.tc.task01.main.Main.main(Main.java:70)
2020-12-19 09:57:00 jdbc[18]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
INSERT INTO oven_table (id, PowerConsumption, Weight,Capacity) VALUES (1234, 5, 6,7) [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:703)
	at org.h2.command.Parser.parseColumn(Parser.java:1450)
	at org.h2.command.Parser.parseColumnList(Parser.java:1435)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1804)
	at org.h2.command.Parser.parseInsert(Parser.java:1749)
	at org.h2.command.Parser.parsePrepared(Parser.java:954)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:126)
	at by.tc.task01.main.Main.main(Main.java:92)
2020-12-19 09:59:17 jdbc[18]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column count does not match; SQL statement:
INSERT INTO oven_table ( PowerConsumption, Weight,Capacity,Depth,Height,Width) VALUES ( 5, 6,7,8,9) [21002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:319)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:126)
	at by.tc.task01.main.Main.main(Main.java:92)
2020-12-19 10:55:37 jdbc[19]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.Uppend(ExchangeDB.java:117)
	at by.tc.task01.main.Main.main(Main.java:77)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 11 more
2020-12-19 10:55:37 jdbc[19]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.Uppend(ExchangeDB.java:117)
	at by.tc.task01.main.Main.main(Main.java:77)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 11 more
2020-12-19 10:55:37 jdbc[19]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.Uppend(ExchangeDB.java:117)
	at by.tc.task01.main.Main.main(Main.java:77)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 11 more
2020-12-19 10:56:20 jdbc[19]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.Uppend(ExchangeDB.java:117)
	at by.tc.task01.main.Main.main(Main.java:77)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 11 more
2020-12-19 10:56:20 jdbc[19]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.Uppend(ExchangeDB.java:117)
	at by.tc.task01.main.Main.main(Main.java:77)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 11 more
2020-12-19 10:56:20 jdbc[19]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.Uppend(ExchangeDB.java:117)
	at by.tc.task01.main.Main.main(Main.java:77)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 11 more
2020-12-19 10:57:38 jdbc[19]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.Uppend(ExchangeDB.java:117)
	at by.tc.task01.main.Main.main(Main.java:77)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 11 more
2020-12-19 10:57:38 jdbc[19]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.Uppend(ExchangeDB.java:117)
	at by.tc.task01.main.Main.main(Main.java:77)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 11 more
2020-12-19 10:57:38 jdbc[19]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.Uppend(ExchangeDB.java:117)
	at by.tc.task01.main.Main.main(Main.java:77)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 11 more
2020-12-19 18:18:02 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:27)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 22 more
2020-12-19 18:18:02 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.getConnection(ExchangeDB.java:24)
	at by.tc.task01.repository.BaseTable.<init>(BaseTable.java:19)
	at by.tc.task01.repository.Oven.<init>(Oven.java:11)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:54)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:27)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
2020-12-19 18:21:17 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:27)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 22 more
2020-12-19 18:21:17 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.getConnection(ExchangeDB.java:24)
	at by.tc.task01.repository.BaseTable.<init>(BaseTable.java:19)
	at by.tc.task01.repository.Oven.<init>(Oven.java:11)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:54)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:27)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
2020-12-19 18:27:08 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 22 more
2020-12-19 18:27:08 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.getConnection(ExchangeDB.java:24)
	at by.tc.task01.repository.BaseTable.<init>(BaseTable.java:19)
	at by.tc.task01.repository.Oven.<init>(Oven.java:11)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:54)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
2020-12-19 19:36:06 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 22 more
2020-12-19 19:36:06 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.getConnection(ExchangeDB.java:24)
	at by.tc.task01.repository.BaseTable.<init>(BaseTable.java:19)
	at by.tc.task01.repository.Oven.<init>(Oven.java:11)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:54)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
2020-12-19 20:48:10 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 22 more
2020-12-19 20:48:10 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.getConnection(ExchangeDB.java:24)
	at by.tc.task01.repository.BaseTable.<init>(BaseTable.java:19)
	at by.tc.task01.repository.Oven.<init>(Oven.java:11)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:54)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
2020-12-19 21:04:31 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 22 more
2020-12-19 21:04:31 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.getConnection(ExchangeDB.java:24)
	at by.tc.task01.repository.BaseTable.<init>(BaseTable.java:19)
	at by.tc.task01.repository.Oven.<init>(Oven.java:11)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:54)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:32)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
2020-12-21 14:50:27 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:33)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 22 more
2020-12-21 14:50:27 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.getConnection(ExchangeDB.java:24)
	at by.tc.task01.repository.BaseTable.<init>(BaseTable.java:19)
	at by.tc.task01.repository.Oven.<init>(Oven.java:11)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:54)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:33)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
2020-12-21 17:47:43 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:47:43 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:47:43 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:47:43 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:47:43 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:47:43 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:55:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:55:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:55:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:55:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:55:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 17:55:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:28)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:34)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 19:29:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 19:29:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 19:29:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 19:29:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 19:29:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 19:29:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:05:39 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:05:39 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:05:39 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:05:39 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:05:39 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:05:39 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:22:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:22:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:22:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:22:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:22:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:22:37 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:30:13 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:30:13 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:30:13 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:30:13 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:30:13 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:30:13 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:32:35 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:32:35 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:32:35 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:32:35 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:32:35 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:32:35 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:59)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:43:49 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:43:49 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:43:49 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:43:49 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:43:49 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:43:49 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:46:54 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:46:54 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:46:54 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:46:54 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:46:54 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 20:46:54 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 21:07:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 21:07:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 21:07:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 21:07:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 21:07:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 21:07:06 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:17:46 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:17:47 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:17:47 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:17:47 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:17:47 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:17:47 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:17:51 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.getConnection(ExchangeDB.java:24)
	at by.tc.task01.repository.BaseTable.<init>(BaseTable.java:19)
	at by.tc.task01.repository.Laptop.<init>(Laptop.java:8)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:56)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:31)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:E:/new_doc/Java/jwd-task01-template_v2/db/exchange.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1075)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 26 more
2020-12-21 22:18:41 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:48)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:18:41 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:48)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:18:41 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:48)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:18:41 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:48)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:18:41 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:48)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
2020-12-21 22:18:41 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at by.tc.task01.ExchangeDB.<init>(ExchangeDB.java:32)
	at by.tc.task01.dao.impl.SetDataBase.<init>(SetDataBase.java:20)
	at by.tc.task01.service.impl.ApplianceServiceImpl.find(ApplianceServiceImpl.java:48)
	at by.tc.task01.main.Main.main(Main.java:60)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 13 more
